server:
    port: 9080
    context-path: /base

spring:
    thymeleaf:
        cache: false
        cache-period: 0
        
    template:
        cache: false
    
    http:
        multipart:
            max-file-size: 2048Mb
            max-request-size: 2048Mb
            
    kafka:
        bootstrap-servers: 127.0.0.1:9092
        producer:
            batch-size: 1000
        consumer:
            group-id: base
        template:
            default-topic: my-topic
        listener:
            concurrency: 5

management:
    port: 9081 
    security:
        enabled: false

logging:
    level:
        root: INFO
    file: logs/base.log

file-path: G://backup

#restful urls
user-urls: ["http://192.168.1.6:9003", "http://localhost:9003"]

#layout
layout: content
full-layout: full-layout

#cas configurations
cas-server: http://127.0.0.1:8080/cas
cas-service: http://127.0.0.1:9080/base/login/cas
cas-login: http://127.0.0.1:8080/cas/login
cas-logout: http://127.0.0.1:8080/cas/logout?service=http://127.0.0.1:9080/base