server:
    port: 8080
    context-path: /base

spring:
    thymeleaf:
        cache: false
        cache-period: 0
        
    template:
        cache: false
    
    http:
        multipart:
            max-file-size: 1024Mb
            max-request-size: 1024Mb
            
    kafka:
        bootstrap-servers: 192.168.1.7:9092
        producer:
            batch-size: 1000
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
            group-id: base
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        template:
            default-topic: my-topic
        listener:
            concurrency: 5

management:
    port: 8081 
    security:
        enabled: false

logging:
    level:
        root: INFO
    file: logs/base.log

file-path: G://backup

#restful urls
user-urls: ["http://qingdao.gclasscn.com:9003", "http://localhost:9003"]

#layout
layout: content
full-layout: full-layout

#cas configurations
cas-server: http://qingdao.gclasscn.com/cas
cas-service: http://127.0.0.1:8080/base/login/cas
cas-login: http://qingdao.gclasscn.com/cas/login
cas-logout: http://qingdao.gclasscn.com/cas/logout?service=http://127.0.0.1:8080/base